name: CI/CD Pipeline with SonarQube

on:
  push:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 11 (for SonarScanner)
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Install Node.js dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: Run SonarQube Scanner
      uses: SonarSource/sonarcloud-github-action@v1.4
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
